### PR TITLE
Add CircleCI workflow

### PR DESCRIPTION
**Pull request by drazisil**

### CODE REVIEW

**Comment by greenpau** [comment]
hi @drazisil , how about adding Github actions instead of Circle CI?

**Comment by drazisil** [comment]
Opps, this was not supposed to be a PR to upstream yet. 🤦

**Comment by drazisil** [comment]
In answer to the question, I'm more used to CircleCI, and it's the only CI I'm aware of that has build artifacts.

**Comment by greenpau** [comment]
> In answer to the question, I'm more used to CircleCI, and it's the only CI I'm aware of that has build artifacts.

@drazisil , see how to build artifacts [here](https://github.com/greenpau/caddy-auth-jwt/blob/6cdfa3290afde2821526ec27c4f0d1f740e4c066/.github/workflows/main.yml#L59-L63). It is super easy with GH actions.

**Comment by drazisil** [comment]
I need this built under Alpine, do you know offhand if GH Actions supports that platform?

(or, if there is any chance this will even build under Alpine period?)

**Comment by greenpau** [comment]
> I need this built under Alpine, do you know offhand if GH Actions supports that platform?

https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-a-docker-hub-action

> (or, if there is any chance this will even build under Alpine period?)

musl comes to mind ...

You would need `musl-gcc wrapper`. See https://www.musl-libc.org/how.html

**Pull request closed without merging**
